### ISSUE TITLE
exception when running on arm64 ubuntu jammy system

### ISSUE THREAD

**Issue by theofficialgman** [tseliot/ubuntu-drivers-common#89]
```
ubuntu-drivers debug
=== log messages from detection ===
DEBUG:root:Skipping check for oem-sutton-cappy-meta since it does not depend on video abi
DEBUG:root:Skipping check for rtl8812au-dkms since it does not depend on video abi
DEBUG:root:Skipping check for oem-sutton-cais-meta since it does not depend on video abi
DEBUG:root:Skipping check for oem-sutton-balint-meta since it does not depend on video abi
DEBUG:root:Cannot find xserver-xorg-video-nvidia-525-open package in the cache. Cannot check ABI
DEBUG:root:Skipping check for open-vm-tools-desktop since it does not depend on video abi
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/UbuntuDrivers/detect.py", line 258, in packages_for_modalias
    cache_map = packages_for_modalias.cache_maps[apt_cache_hash]
KeyError: 34254728679

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/bin/ubuntu-drivers", line 513, in <module>
    greet()
  File "/usr/lib/python3/dist-packages/click/core.py", line 1128, in __call__
    return self.main(*args, **kwargs)
  File "/usr/lib/python3/dist-packages/click/core.py", line 1053, in main
    rv = self.invoke(ctx)
  File "/usr/lib/python3/dist-packages/click/core.py", line 1659, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/lib/python3/dist-packages/click/core.py", line 1395, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/lib/python3/dist-packages/click/core.py", line 754, in invoke
    return __callback(*args, **kwargs)
  File "/usr/lib/python3/dist-packages/click/decorators.py", line 84, in new_func
    return ctx.invoke(f, obj, *args, **kwargs)
  File "/usr/lib/python3/dist-packages/click/core.py", line 754, in invoke
    return __callback(*args, **kwargs)
  File "/usr/bin/ubuntu-drivers", line 499, in debug
    command_debug(config)
  File "/usr/bin/ubuntu-drivers", line 314, in command_debug
    packages = UbuntuDrivers.detect.system_driver_packages(
  File "/usr/lib/python3/dist-packages/UbuntuDrivers/detect.py", line 504, in system_driver_packages
    for p in packages_for_modalias(apt_cache, alias):
  File "/usr/lib/python3/dist-packages/UbuntuDrivers/detect.py", line 260, in packages_for_modalias
    cache_map = _apt_cache_modalias_map(apt_cache)
  File "/usr/lib/python3/dist-packages/UbuntuDrivers/detect.py", line 222, in _apt_cache_modalias_map
    if not _check_video_abi_compat(apt_cache, package):
  File "/usr/lib/python3/dist-packages/UbuntuDrivers/detect.py", line 153, in _check_video_abi_compat
    for dep_list in candidate.depends_list_str.get('Depends'):
AttributeError: 'NoneType' object has no attribute 'depends_list_str'
```

same issue with `list`. I just show debug here incase there is any helpful info included.

**Comment by tseliot** [comment]
which version of ubuntu-drivers-common are you using?

**Comment by theofficialgman** [comment]
the current version in jammy-updates. so `1:0.9.6.2~0.22.04.`

**Comment by theofficialgman** [comment]
Attempted to build the latest release `1:0.9.7.6` and still having the same issue

```
test_system_device_drivers_detect_plugins (test_ubuntu_drivers.DetectTest)
system_device_drivers() includes custom detection plugins ... ERROR
...
test_system_driver_packages_detect_plugins (test_ubuntu_drivers.DetectTest)
system_driver_packages() includes custom detection plugins ... ERROR
...
test_system_driver_packages_performance (test_ubuntu_drivers.DetectTest)
system_driver_packages() performance for a lot of modaliases ... ERROR
```

```
======================================================================
ERROR: test_system_device_drivers_detect_plugins (test_ubuntu_drivers.DetectTest)
system_device_drivers() includes custom detection plugins
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/tmp/drivers/ubuntu-drivers-common-0.9.7.6/UbuntuDrivers/detect.py", line 291, in packages_for_modalias
    cache_map = packages_for_modalias.cache_maps[apt_cache_hash]
KeyError: 34219763672

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/tmp/drivers/ubuntu-drivers-common-0.9.7.6/tests/test_ubuntu_drivers.py", line 3462, in test_system_device_drivers_detect_plugins
    res = UbuntuDrivers.detect.system_device_drivers(sys_path=self.umockdev.get_sys_dir())
  File "/tmp/drivers/ubuntu-drivers-common-0.9.7.6/UbuntuDrivers/detect.py", line 927, in system_device_drivers
    for pkg, pkginfo in system_driver_packages(apt_cache, sys_path,
  File "/tmp/drivers/ubuntu-drivers-common-0.9.7.6/UbuntuDrivers/detect.py", line 591, in system_driver_packages
    for p in packages_for_modalias(apt_cache, alias):
  File "/tmp/drivers/ubuntu-drivers-common-0.9.7.6/UbuntuDrivers/detect.py", line 293, in packages_for_modalias
    cache_map = _apt_cache_modalias_map(apt_cache)
  File "/tmp/drivers/ubuntu-drivers-common-0.9.7.6/UbuntuDrivers/detect.py", line 224, in _apt_cache_modalias_map
    if not _check_video_abi_compat(apt_cache, package):
  File "/tmp/drivers/ubuntu-drivers-common-0.9.7.6/UbuntuDrivers/detect.py", line 155, in _check_video_abi_compat
    for dep_list in candidate.depends_list_str.get('Depends'):
AttributeError: 'NoneType' object has no attribute 'depends_list_str'

======================================================================
ERROR: test_system_driver_packages_detect_plugins (test_ubuntu_drivers.DetectTest)
system_driver_packages() includes custom detection plugins
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/tmp/drivers/ubuntu-drivers-common-0.9.7.6/UbuntuDrivers/detect.py", line 291, in packages_for_modalias
    cache_map = packages_for_modalias.cache_maps[apt_cache_hash]
KeyError: 34219763630

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/tmp/drivers/ubuntu-drivers-common-0.9.7.6/tests/test_ubuntu_drivers.py", line 3388, in test_system_driver_packages_detect_plugins
    res = UbuntuDrivers.detect.system_driver_packages(sys_path=self.umockdev.get_sys_dir())
  File "/tmp/drivers/ubuntu-drivers-common-0.9.7.6/UbuntuDrivers/detect.py", line 591, in system_driver_packages
    for p in packages_for_modalias(apt_cache, alias):
  File "/tmp/drivers/ubuntu-drivers-common-0.9.7.6/UbuntuDrivers/detect.py", line 293, in packages_for_modalias
    cache_map = _apt_cache_modalias_map(apt_cache)
  File "/tmp/drivers/ubuntu-drivers-common-0.9.7.6/UbuntuDrivers/detect.py", line 224, in _apt_cache_modalias_map
    if not _check_video_abi_compat(apt_cache, package):
  File "/tmp/drivers/ubuntu-drivers-common-0.9.7.6/UbuntuDrivers/detect.py", line 155, in _check_video_abi_compat
    for dep_list in candidate.depends_list_str.get('Depends'):
AttributeError: 'NoneType' object has no attribute 'depends_list_str'

======================================================================
ERROR: test_system_driver_packages_performance (test_ubuntu_drivers.DetectTest)
system_driver_packages() performance for a lot of modaliases
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/tmp/drivers/ubuntu-drivers-common-0.9.7.6/UbuntuDrivers/detect.py", line 291, in packages_for_modalias
    cache_map = packages_for_modalias.cache_maps[apt_cache_hash]
KeyError: 34219763665

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/tmp/drivers/ubuntu-drivers-common-0.9.7.6/tests/test_ubuntu_drivers.py", line 190, in test_system_driver_packages_performance
    UbuntuDrivers.detect.system_driver_packages(sys_path=self.umockdev.get_sys_dir())
  File "/tmp/drivers/ubuntu-drivers-common-0.9.7.6/UbuntuDrivers/detect.py", line 591, in system_driver_packages
    for p in packages_for_modalias(apt_cache, alias):
  File "/tmp/drivers/ubuntu-drivers-common-0.9.7.6/UbuntuDrivers/detect.py", line 293, in packages_for_modalias
    cache_map = _apt_cache_modalias_map(apt_cache)
  File "/tmp/drivers/ubuntu-drivers-common-0.9.7.6/UbuntuDrivers/detect.py", line 224, in _apt_cache_modalias_map
    if not _check_video_abi_compat(apt_cache, package):
  File "/tmp/drivers/ubuntu-drivers-common-0.9.7.6/UbuntuDrivers/detect.py", line 155, in _check_video_abi_compat
    for dep_list in candidate.depends_list_str.get('Depends'):
AttributeError: 'NoneType' object has no attribute 'depends_list_str'

----------------------------------------------------------------------
Ran 56 tests in 598.163s
```

all other tests pass

**Comment by tseliot** [comment]
Thanks for reporting. I will try to reproduce the problem here.

**Comment by psucodervn** [comment]
Hi, I'm facing the same issue. Do you guys have any update on this?

**Comment by genevera** [comment]
This is blocking me also
